apiVersion: apps/v1
kind: Deployment
metadata:
  name: kind-deployment
  labels:
    app: go
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rsgo
  template:
    metadata:
      labels:
        app: rsgo
    spec:
      containers:
        - name: go-webapi-for-gke-study
          image: sky0621dhub/go-webapi-for-gke-study:v0.2
          ports:
            - containerPort: 80
