---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order1-deployment
  annotations:
    annotation1: val1
    annotation2: val2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: go-webapi-for-gke-study
          image: sky0621dhub/go-webapi-for-gke-study:v0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-2-deployment
spec:
  type: LoadBalancer
  ports:
    - name: "http-pprt"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    app: sample-app
